apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.5/manifests/install.yaml
- https://github.com/argoproj-labs/applicationset/manifests/crds?ref=v0.2.0
- https://github.com/argoproj-labs/applicationset/manifests/base?ref=v0.2.0

namespace: ci-cd