
workflow: 
  serviceAccount:
    create: true

controller: 
  workflowNamespaces:
    - ci-cd
  logging:
    level: debug

server:
  enabled: true
  ingress: 
    enabled: true
    https: false
    annotations: 
      kubernetes.io/ingress.class: nginx
      # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      kubernetes.io/tls-acme: "true"
      # external-dns.alpha.kubernetes.io/hostname: argocd.$CLIENT_DOMAIN_URL
      cert-manager.io/cluster-issuer: letsencrypt-production-aws
    hosts:
      - argowf.odysseycloud.io
    tls:
      - hosts:
          - argowf.odysseycloud.io
        secretName: letsencrypt-argo-workflows-odysseycloud-io-prod

  sso: 
    issuer: https://accounts.google.com
    redirectUrl: https://argowf.odysseycloud.io/oauth2/callback