apiVersion: v2
name: cert-manager
namespace: dns-infra
description: cert-manager Helm chart for Kubernetes
type: application
version: 1.6.1
appVersion: "1.6.1"

dependencies:
- name: cert-manager
  chart: jetstack/cert-manager
  version: 1.6.1
  repository: https://charts.jetstack.io
  values:
    - production-cert-manager-values.yaml
