apiVersion: v2
name: argocd-applicationset
namespace: ci-cd
description: argocd-applicationset Helm chart for Kubernetes
type: application
version: 1.6.0
appVersion: "v0.2.0"

dependencies:
- name: argocd-applicationset
  chart: argo/argocd-applicationset
  version: 0.2.0
  condition: argocd-applicationset.enabled
  repository: https://argoproj.github.io/argo-helm
