name: Idea❓
description: Suggest your issue here🥇
title: "[Issue]: Your Issue's brief Description goes here"
labels: [enhancement, help-wanted]
assignees:
  - unassigned
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill in your idea. It will genuinely benefit the community
  - type: input
    attributes:
      label: Idea
      description: Can you please elaborate your new Idea here?
      placeholder: Tell us what you'd like to have briefly.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Elaboration
      description: Elaborately, explain your idea/
      placeholder: Tell us what you wish to see.
    validations:
      required: true
  - type: textarea
    id: multimedia
    attributes:
      label: Further Details/ Image and Video Based suggestion
      description: Please give us the image/video if applicable
      placeholder: Please upload your multimedia(screenshots and video) here
      