name: Issue Template❌
description: File/Create an Issue
title: "[Issue]: Your Issue's brief Description goes here"
labels: [bug,help wanted, good first issue]
assignees:
  - unassigned
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Bug/Issue report!
  - type: input
    attributes:
      label: Issue 
      description: Can you please elaborate your Issue here?
      placeholder: Tell us what you found.
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Is this a browser specific issue? If so which browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: multimedia
    attributes:
      label: Further Details
      description: Please give us the image/video of the issue
      placeholder: Please upload your multimedia(screenshots and video) here
      