apiVersion: v2
name: keptn
namespace: keptn
description: Keptn Helm chart for Kubernetes
type: application
version: 0.8.7
appVersion: "0.8.7"

dependencies:
- name: keptn
  chart: keptn/keptn
  version: 0.8.7
  repository: https://storage.googleapis.com/keptn-installer
  values:
    - common-keptn-values.yaml
  # hooks:
  #     - events: ["post-install"]
  #       command: "kubectl"
  #       args: ["apply", "--validate=true", "--filename=ingress.yaml"]

- name: jmeter-service
  chart: keptn/jmeter-service
  version: 0.9.0
  repository: https://storage.googleapis.com/keptn-installer
  values:
    - common-jmeter-values.yaml

- name: helm-service
  chart: keptn/helm-service
  version: 0.9.0
  repository: https://storage.googleapis.com/keptn-installer
  values:
    - common-helm-service-values.yaml