control-plane:
  enabled: true
  apiGatewayNginx:
    type: ClusterIP
    port: 80

continuous-delivery:
  enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "false"
  host: "keptn.ortelius.io"
  path: /
  pathType: Prefix
  tls:
    []
  