---
apiVersion: v1
kind: Namespace
metadata:
  name: secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: argo
---
apiVersion: v1
kind: Namespace
metadata:
  name: dns-infra
---
apiVersion: v1
kind: Namespace
metadata:
  name: keptn
---
apiVersion: v1
kind: Namespace
metadata:
  name: ortelius
---