apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ortelius
  namespace: ci-cd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Ortelius Project

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://aks-c452c5c4.0ed4e465-53d1-43cc-b016-12689a743be0.privatelink.eastus.azmk8s.io:443
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'    
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'    
