apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-infra-setup
  namespace: ci-cd
spec:
  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/ortelius/ortelius-kubernetes.git
          revision: HEAD
          directories:
          - path: kube-infra/kustomize/observability/*
      - list:
          elements:
          - cluster: production
            url: https://aks-96cc8329.0bdd7a85-0827-4b5f-a665-5294ca534810.privatelink.eastus.azmk8s.io:443
            values:
              CLIENT_ENVIRONMENT: production             
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: ortelius
      source:
        repoURL: https://github.com/ortelius/ortelius-kubernetes.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            - '{{cluster}}-{{path.basename}}-values.yaml'
      destination:
        server: https://aks-96cc8329.0bdd7a85-0827-4b5f-a665-5294ca534810.privatelink.eastus.azmk8s.io:443
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: 
            prune: true 
            selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
        syncOptions:     # Sync options which modifies sync behavior
        - CreateNamespace=true     
