repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

environments: 
  production:
    values:

releases:
  - name: sealed-secrets-controller
    namespace: security
    chart: sealed-secrets/sealed-secrets 
    version: 1.16.1
    values:
      - ../kube-infra/helm/security/sealed-secrets/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-sealed-secrets-values.yaml
