repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: jetstack
    url: https://charts.jetstack.io

values:
  - sealed-secrets:
      enabled: true
  - cert-manager:
      enabled: true
      
environments:
  production:
    values:
      - sealed-secrets:
          enabled: true
      - cert-manager:
          enabled: true

releases:
  - name: sealed-secrets-controller
    namespace: security
    chart: sealed-secrets/sealed-secrets 
    version: 1.16.1
    condition: sealed-secrets.enabled
    values:
      - ../kube-infra/helm/security/sealed-secrets/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-sealed-secrets-values.yaml

  - name: cert-manager
    namespace: dns-infra
    chart: jetstack/cert-manager
    version: 1.6.1
    condition: cert-manager.enabled
    values:
      - ../kube-infra/helm/dns-infra/cert-manager/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-cert-manager-values.yaml
