repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

values:
  - argo-cd:
      enabled: true 
      
environments:
  production:
    values:
      - argo-cd:
          enabled: true


releases:
  - name: argo-cd
    namespace: argo
    chart: argo/argo-cd
    version: 3.17.5
    condition: argo-cd.enabled
    values:
      - values/{{ requiredEnv "CLIENT_ENVIRONMENT" }}/argo-cd.yaml

  - name: argocd-applicationset
    namespace: argo
    chart: argo/argocd-applicationset
    version: 1.4.0
    condition: argo-cd.enabled 
    values:
      - ../k8s-infra/argo/argocd-applicationset/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-argocd-applicationset-values.yaml 

  - name: cert-manager
    namespace: dns-infra
    chart: jetstack/cert-manager
    version: 1.4.0
    values:
      - ../k8s-infra/dns-infra/cert-manager/common-cert-manager-values.yaml

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 3.34.0
    values:
      - ../k8s-infra/dns-infra/ingress-nginx/{{ requiredEnv "CLIENT_ENVIRONMENT" }}-ingress-nginx-values.yaml 